languageCode = "en-us"
title = "Luca Di Stefano"
theme = "avicenna"
timeout=3000
ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["section", "RSS", "taxonomy", "term", "sitemap", "robotsTXT", "404"]

[params]
  subtitle = "Post-doctoral researcher"
  charset = "utf-8"
  Description = "Post-doctoral researcher"
  interests="Software verification, Model checking, Multi-agent systems, Formal semantics, Process calculi"
  cv_name= "LucaDiStefano_CV.pdf"
  picture_name = "profile.jpg"
  blog="http://lou1306.github.io/en"
  dblp="https://dblp.uni-trier.de/pid/215/9758.html"

[[params.affilation]]
  name = "Univeristy of Gothenburg and Chalmers"
  position = "Post-doctoral researcher"
  contact = "lucad@chalmers.se"


[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/lou1306"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/lou1306/"


[[params.introduction.paragraph]]
  text="""
  My research focuses on the specification of complex
  collective systems (such as multi-agent systems, robot swarms, stigmergies,
  and so on) and their analysis via state-of-the-art verification techniques. 
   """

[[params.cv.paragraph]]
  from = "May 2022"
  to = "Present time"
  text="""Post-doctoral researcher at the [d-SynMA team](https://dsynma.bitbucket.io/) (University of Gothenburg and Chalmers, Gothenburg, Sweden)."""

[[params.cv.paragraph]]
  from = "November 2020"
  to = "April 2022"
  text="""Post-doctoral researcher at [CONVECS](https://convecs.inria.fr) (INRIA and LIG, Grenoble, France)."""

[[params.cv.paragraph]]
  from = "December 2019"
  to = "October 2020"
  text="""Holder of a research grant on "Verification of Emerging Properties in
      Collective Adaptive Systems" at [SysMA](https://sysma.imtlucca.it/) (IMT School for Advanced Studies, Lucca, Italy).
      """

[[params.cv.paragraph]]
  from = "March 2019"
  to = "July 2019"
  text="""Visiting PhD student at [CONVECS](https://convecs.inria.fr) (INRIA and LIG, Grenoble, France)."""

[[params.cv.paragraph]]
  from = "October 2016"
  to = "November 2020"
  text="""PhD in Computer Science at [Gran Sasso Science Institute](https://gssi.it) (L'Aquila, Italy)."""
   
[[params.cv.paragraph]]
  from = "March 2014"
  to = "October 2016"
  text="""Master's Degree in Computer and Systems Engineering at [DISIM](https://www.disim.univaq.it/) (University of L'Aquila, Italy)."""


[[params.teaching.paragraph]]
  from = "March 2022"
  to = "April 2022"
  text=""""Modelling and Verification", [Polytech Paris-Saclay](https://www.polytech.universite-paris-saclay.fr/).
      36-hour course for Master students in Computer Science Engineering
      (*filière apprentissage*). Held as a supply teacher (*intervenant vacataire*). 

      """

[[params.teaching.paragraph]]
  from = "April 2021"
  to = "May 2021"
  text=""""Modelling and Verification", [Polytech Paris-Saclay](https://www.polytech.universite-paris-saclay.fr/).
      36-hour course for Master students in Computer Science Engineering
      (*filière apprentissage*). Held remotely as a supply teacher (*intervenant vacataire*). Topics:

* Communicating automata, behavioural equivalences;
* Timed automata;
* Process algebras, temporal logics, model checking;
* Model-based testing;
* Lab sessions involving [UPPAAL](https://uppaal.org/), [CADP](https://cadp.inria.fr/), [TESTOR](http://convecs.inria.fr/software/testor/).
      """

[[params.projects]]
  [[params.projects.project]]
    name = "SLiVER - A verification tool for LAbS systems"
    description  = """
SLiVER is a tool for the analysis of multi-agent systems specified in the LAbS language.
Currently, it support under-approximate analysis via bounded model checking, or analisys
of the full state space via explicit-state model checking. Moreover, the C programs
generated from SLiVER can be analyzed with several other techniques.
    """
    code_link = "https://github.com/labs-lang/sliver"
  
  [[params.projects.project]]
    name = "LAbS - A Language with Attribute-Based Stigmergies"
    description  = """
LAbS is a small language for multi-agent systems with stigmergic interaction.
The term "stigmergy" denotes a mechanism that allows agents to influence
each other's behavior by leaving traces in a shared medium.
In LAbS, such medium is provided by a distributed data structure that also
supports attribute-based constraints.
Thus, specific conditions for interaction between agents can be expressed in
the form of predicates over their exposed features.
This combination allows to naturally model a wide selection of systems.
    """
    code_link = "https://github.com/labs-lang/labs"
      

[[params.publications]]
  year="2022"

  [[params.publications.paper]]
    name = "Automated replication of tuple spaces via static analysis"
    authors = "Rocco De Nicola, Luca Di Stefano, Omar Inverso, Aline Uwimbabazi"
    dest  = "Science of Computer Programming, vol. 223"
    link = "https://doi.org/10.1016/j.scico.2022.102863"

  [[params.publications.paper]]
    name = "Process Algebras and Flocks of Birds"
    authors = "Rocco De Nicola, Luca Di Stefano, Omar Inverso, Serenella Valiani"
    dest  = "A journey from process algebra via timed automata to model learning - Essays dedicated to frits vaandrager on the occasion of his 60th birthday"
    link = "https://doi.org/10.1007/978-3-031-15629-8_27"

  [[params.publications.paper]]
    name = "Modelling Flocks of Birds from the Bottom Up"
    authors = "Rocco De Nicola, Luca Di Stefano, Omar Inverso, Serenella Valiani"
    dest  = "To appear in ISoLA 2022"
    #link = "https://doi.org/10.1145/3490387"

  [[params.publications.paper]]
    name = "Verification of Distributed Systems via Sequential Emulation"
    authors = "Luca Di Stefano, Rocco De Nicola, Omar Inverso"
    dest  = "ACM Transactions on Software Engineering and Methodology, vol. 31"
    link = "https://doi.org/10.1145/3490387"

[[params.publications]]
  year="2021"

  [[params.publications.paper]]
    name = "Verifying temporal properties of stigmergic collective systems using CADP"
    authors = "Luca Di Stefano, Frédéric Lang"
    dest  = "ISoLA 2021"
    link = "https://doi.org/10.1007/978-3-030-89159-6_29"
    pdf_link = "https://hal.inria.fr/hal-03385131/document"

[[params.publications]]
  year="2020"

  [[params.publications.paper]]
    name = "Modelling and Verification of Multi-Agent Systems via Sequential Emulation"
    authors = "Luca Di Stefano, advisors: Rocco De Nicola and Omar Inverso"
    dest  = "PhD thesis"
    link = "https://iris.gssi.it/handle/20.500.12571/10181"
    pdf_link = "https://iris.gssi.it/retrieve/handle/20.500.12571/10181/3143/2020_DiStefano.pdf"

  [[params.publications.paper]]
    name = "Combining SLiVER with CADP to Analyze Multi-agent Systems"
    authors = "Luca Di Stefano, Frédéric Lang, Wendelin Serwe"
    dest  = "COORDINATION 2020"
    link = "https://doi.org/10.1007/978-3-030-50029-0_23"
    pdf_link = "http://convecs.inria.fr/doc/publications/DiStefano-Lang-Serwe-20.pdf"
    slides_link = "http://convecs.inria.fr/doc/presentations/DiStefano-COORDINATION-20.pdf"
    video_link = "https://youtu.be/4D5KdkM9zA4"

  [[params.publications.paper]]
    name = "Multi-agent systems with virtual stigmergy"
    authors = "Rocco De Nicola, Luca Di Stefano, Omar Inverso"
    dest  = "Science of Computer Programming, vol. 187"
    link = "https://doi.org/10.1016/j.scico.2019.102345"
    
[[params.publications]]
  year="2018"

  [[params.publications.paper]]
    name = "Toward Formal Models and Languages for Verifiable Multi-Robot Systems"
    authors = "Rocco De Nicola, Luca Di Stefano, Omar Inverso"
    dest  = "Frontiers in Robotics and Ai, vol. 5"
    link = "https://doi.org/10.3389/frobt.2018.00094"
    
[[params.publications]]
  year="2017"

  [[params.publications.paper]]
    name = "Reactive Obstacle Avoidance for Multicopter UAVs via Evaluation of Depth Maps"
    authors = "Luca Di Stefano, Eliseo Clementini, Enrico Stagnini"
    dest  = "COSIT Workshops and Posters 2017"
    link = "https://doi.org/10.1007/978-3-319-63946-8_10"


[[params.reports]]
  year="2022"

  [[params.reports.report]]
    name = "Compositional Verification of Priority Systems using Sharp Bisimulation"
    authors = "Luca Di Stefano, Frédéric Lang"
    dest  = "INRIA Research report"
    link = "https://hal.inria.fr/hal-03640683"
    pdf_link = "https://hal.inria.fr/hal-03640683/document"

